title: ConnorDev | Bug Bounty Portfolio
description: Security Research & Bug Bounty Reports by ConnorDev.
show_downloads: false

# No theme - fully custom CSS
# remote_theme: pages-themes/hacker@v0.2.0

baseurl: ""
url: "https://connordev1337.github.io"

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Researchers Data
researchers:
  ivan:
    name: "Iván Córcoles Martínez"
    email: "connordev@protonmail.com"
    bugcrowd: "https://bugcrowd.com/h/ConnorDev"
  diego:
    name: "Diego García Ayala"
    email: "diego.garaya02@gmail.com"
    bugcrowd: "https://bugcrowd.com/h/sl4sh1t0"

exclude:
  - README.md
  - .gitignore
  - .git/
  - tmp/